DUNGEONS = [
    "Test Dungeon",
    "Beach Cave",
    "Beach Cave Pit",
    "Drenched Bluff",
    "Mt. Bristle",
    "Mt. Bristle Peak",
    "Waterfall Cave",
    "Apple Woods",
    "Craggy Coast",
    "Side Path",
    "Mt. Horn",
    "Rock Path",
    "Foggy Forest",
    "Forest Path",
    "Steam Cave",
    "Upper Steam Cave",
    "Steam Cave Peak",
    "Amp Plains",
    "Far Amp Plains",
    "Amp Clearing",
    "Northern Desert",
    "Quicksand Cave",
    "Quicksand Pit",
    "Underground Lake",
    "Crystal Cave",
    "Crystal Crossing",
    "Crystal Lake",
    "Chasm Cave",
    "Dark Hill",
    "Sealed Ruin",
    "Deep Sealed Ruin",
    "Sealed Ruin Pit",
    "Dusk Forest",
    "Deep Dusk Forest",
    "Treeshroud Forest",
    "Brine Cave",
    "Lower Brine Cave",
    "Brine Cave Pit",
    "Hidden Land",
    "Hidden Highland",
    "Old Ruins",
    "Temporal Tower",
    "Temporal Spire",
    "Temporal Pinnacle",
    "Mystifying Forest",
    "Mystifying Forest Clearing",
    "Blizzard Island",
    "Crevice Cave",
    "Lower Crevice Cave",
    "Crevice Cave Pit",
    "Surrounded Sea",
    "Miracle Sea",
    "Deep Miracle Sea",
    "Miracle Seabed",
    "Ice Aegis Cave",
    "Regice Chamber",
    "Rock Aegis Cave",
    "Regirock Chamber",
    "Steel Aegis Cave",
    "Registeel Chamber",
    "Aegis Cave Pit",
    "Regigigas Chamber",
    "Mt. Travail",
    "The Nightmare",
    "Spacial Rift",
    "Deep Spacial Rift",
    "Spacial Rift Bottom",
    "Dark Crater",
    "Deep Dark Crater",
    "Dark Crater Pit",
    "Concealed Ruins",
    "Deep Concealed Ruins",
    "Marine Resort",
    "Bottomless Sea",
    "Bottomless Sea Depths",
    "Shimmer Desert",
    "Shimmer Desert Pit",
    "Mt. Avalanche",
    "Mt. Avalanche Peak",
    "Giant Volcano",
    "Giant Volcano Peak",
    "World Abyss",
    "World Abyss Pit",
    "Sky Stairway",
    "Sky Stairway Apex",
    "Mystery Jungle",
    "Deep Mystery Jungle",
    "Serenity River",
    "Landslide Cave",
    "Lush Prairie",
    "Tiny Meadow",
    "Labyrinth Cave",
    "Oran Forest",
    "Lake Afar",
    "Happy Outlook",
    "Mt. Mistral",
    "Shimmer Hill",
    "Lost Wilderness",
    "Midnight Forest",
    "Zero Isle North",
    "Zero Isle East",
    "Zero Isle West",
    "Zero Isle South",
    "Zero Isle Center",
    "Destiny Tower",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "Oblivion Forest",
    "Treacherous Waters",
    "Southeastern Islands",
    "Inferno Cave",
    "1st Station Pass",
    "2nd Station Pass",
    "3rd Station Pass",
    "4th Station Pass",
    "5th Station Pass",
    "6th Station Pass",
    "7th Station Pass",
    "8th Station Pass",
    "9th Station Pass",
    "Sky Peak Summit Pass",
    "5th Station Clearing",
    "Sky Peak Summit",
    "Star Cave",
    "Deep Star Cave",
    "Deep Star Cave",
    "Star Cave Depths",
    "Star Cave Pit",
    "Murky Forest",
    "Eastern Cave",
    "Fortune Ravine",
    "Fortune Ravine Depths",
    "Fortune Ravine Pit",
    "Barren Valley",
    "Deep Barren Valley",
    "Barren Valley Clearing",
    "Dark Wasteland",
    "Temporal Tower",
    "Temporal Spire",
    "Dusk Forest",
    "Black Swamp",
    "Spacial Cliffs",
    "Dark Ice Mountain",
    "Dark Ice Mountain Peak",
    "Dark Ice Mountain Pinnacle",
    "Icicle Forest",
    "Vast Ice Mountain",
    "Vast Ice Mountain Peak",
    "Vast Ice Mountain Pinnacle",
    "Southern Jungle",
    "Boulder Quarry",
    "Deep Boulder Quarry",
    "Boulder Quarry Clearing",
    "Right Cave Path",
    "Left Cave Path",
    "Limestone Cavern",
    "Deep Limestone Cavern",
    "Limestone Cavern Depths",
    "Spring Cave",
    "Upper Spring Cave",
    "Upper Spring Cave",
    "Middle Spring Cave",
    "Lower Spring Cave",
    "Spring Cave Depths",
    "Spring Cave Pit",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "[M:D1]Dummy",
    "Star Cave",
    "Shaymin Village",
    "Armaldo's Shelter",
    "Luminous Spring",
    "Hot Spring",
    "Rescue",
    "Normal/Fly Maze",
    "Dark/Fire Maze",
    "Rock/Water Maze",
    "Grass Maze",
    "Elec/Steel Maze",
    "Ice/Ground Maze",
    "Fight/Psych Maze",
    "Poison/Bug Maze",
    "Dragon Maze",
    "Ghost Maze",
    "Explorer Maze",
    "Final Maze",
]